# Generated by Django 3.2.16 on 2023-01-25 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendaftaran',
            options={'ordering': ['tanggal_konfirmasi']},
        ),
        migrations.CreateModel(
            name='RekamMedik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_periksa', models.DateField(auto_now_add=True)),
                ('message', models.TextField(blank=True)),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidan.pendaftaran')),
            ],
        ),
    ]
