# Generated by Django 3.2.16 on 2022-11-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='tanggal_konfirmasi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
