# Generated by Django 3.2.16 on 2023-01-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidan', '0002_auto_20230125_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekammedik',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
