# Generated by Django 3.2.16 on 2023-01-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidan', '0003_rekammedik_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='periksa_konfirmasi',
            field=models.BooleanField(default=False),
        ),
    ]
