# Generated by Django 3.2.16 on 2023-06-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidan', '0004_pendaftaran_periksa_konfirmasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='name_anak',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='name_pasangan',
            field=models.CharField(default='', max_length=50),
        ),
    ]
